[controls]
insert_coin = "C"
start_1p    = "1"
start_2p    = "2"
shot_1p     = "SPACE"
shot_2p     = "SPACE"
left_1p     = "A"
left_2p     = "A"
right_1p    = "D"
right_2p    = "D"

[volume]
volume = 64 # 0 - 128

[screen]
width       = 672 # original game resolution multiplied by three (224 * 3)
height      = 768 # 256 * 3
black_color = 0
# Format RGB332 (000_111_00 or 28 = very green)
white_color = 28
fullscreen  = false